ARG BASE_IMAGE="ghcr.io/gbraad-dotfiles/fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

USER root

# for distrobox
RUN dnf install --allowerasing -y \
        bc \
        bzip2 \
        curl \
        diffutils \
        findutils \
        glibc-common \
        gnupg2 \
        gnupg2-smime \
        iproute \
        krb5-libs \
        less \
        lsof \
        ncurses \
        openssh-clients \
        pam \
        pinentry \
        procps-ng \
        shadow-utils \
        sudo \
        time \
        util-linux \
        vte-profile \
        which \
        xz \
        zsh \
        cracklib-dicts \
        glibc-all-langpacks \
        glibc-locale-source \
        hostname \
        iputils \
        keyutils \
        krb5-libs \
        man-db \
        mesa-dri-drivers \
        mesa-vulkan-drivers \
        mtr \
        nss-mdns \
        pigz \
        rsync \
        tcpdump \
        traceroute \
        tree \
        unzip \
        whois \
        xorg-x11-xauth \
        zip \
    && dnf clean all \
    && rm -rf /var/cache/yum

# disable tailscaled as this needs userspace networking
RUN systemctl disable tailscaled
